name: Release
on:
  release:
    types: [edited, published]
    branches:
      - main
      - feature-*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Write secrets.env
        env:
          SECRETS: ${{ secrets.SECRETS_ENV }}
          PIFILE: rhasspy.Pifile
        run: |
          echo $SECRETS > $(dirname $PIFILE)/secrets.env

      - name: Build image
        uses: Nature40/pimod@v0.2.2
        with:
          pifile: rhasspy.Pifile
          
      - name: Make tarball
        run: |
          tar -czvf rhasspy.tar.gz rhasspy.img

      - name: Publish binaries  
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'rhasspy.img'
